name: TeamWin [TWRP] Test Builds

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: TWRP Build Matrix
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        device: 
          - { manifest_branch: 'twrp-12.1', device_tree: 'https://github.com/mlm-games/twrp_galaxy_m02s', device_tree_branch: 'twrp-12.1', device_name: 'm02s', makefile_name: 'twrp_m02s', build_target: 'recovery' }
          - { manifest_branch: 'twrp-9.0', device_tree: 'https://github.com/mlm-games/twrp_lenovo_7305x_m7_mt8765_P', device_tree_branch: 'twrp-9.0', device_name: 'mt8765_P', makefile_name: 'omni_mt8765_P', build_target: 'recovery' }
          - { manifest_branch: 'twrp-7.1', device_tree: 'https://github.com/mlm-games/twrp_lenovo_7304F', device_tree_branch: 'twrp-7.1', device_name: '7304F', makefile_name: 'omni_7304F', build_target: 'recovery' }
    steps:
    - name: Clean-up
      uses: rokibhasansagar/slimhub_actions@main

    - name: Set Swap Space (Optional)
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 16

    - name: Build TWRP Recovery
      uses: mlm-games/TWRP-recovery-build-action@main 
      with:
        MANIFEST_BRANCH: '${{ matrix.device.manifest_branch }}'
        DEVICE_TREE: '${{ matrix.device.device_tree }}'
        DEVICE_TREE_BRANCH: '${{ matrix.device.device_tree_branch }}'
        DEVICE_NAME: '${{ matrix.device.device_name }}'
        DEVICE_PATH: 'device/${{ matrix.device.device_name }}'
        MAKEFILE_NAME: '${{ matrix.device.makefile_name }}'
        BUILD_TARGET: '${{ matrix.device.build_target }}'

    - name: Upload Recovery Image
      uses: actions/upload-artifact@v3
      with:
        name: TWRP-Recovery-${{ matrix.device.device_name }}
        path: ${{ env.OUTPUT_DIR }}/*.img
